services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    restart: unless-stopped
    networks:
      - jenkins
    volumes:
      - ~/.jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

  nginx:
    image: nginx:1
    container_name: nginx
    restart: unless-stopped
    networks:
      - jenkins
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/.jenkins:/var/jenkins_home
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./live/<domain>/fullchain.pem:/etc/ssl/fullchain.pem
      - ./live/<domain>/privkey.pem:/etc/ssl/privkey.pem

networks:
  jenkins:
    driver: bridge
